//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4927
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.CompactFramework.Design.Data 2.0.50727.4927 版自动生成。
// 
namespace STL.PDA.UserLogin {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SI_MM028_PDA2SAP_LOGIN_OUTBinding", Namespace="http://www.stlerpproject.com.cn/PDA/MM")]
    public partial class SI_MM028_PDA2SAP_LOGIN_OUTService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public SI_MM028_PDA2SAP_LOGIN_OUTService() {
            this.Url = "http://mail.satellite-petrochemical.com:8000/XISOAPAdapter/MessageServlet?senderParty=&send" +
                "erService=BC_WINCE&receiverParty=&receiverService=&interface=SI_MM028_PDA2SAP_LO" +
                "GIN_OUT&interfaceNamespace=http%3A%2F%2Fwww.stlerpproject.com.cn%2FPDA%2FMM";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", RequestElementName="ZMM_PDA_LOGIN", RequestNamespace="urn:sap-com:document:sap:rfc:functions", ResponseElementName="ZMM_PDA_LOGIN.Response", ResponseNamespace="urn:sap-com:document:sap:rfc:functions", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("RETURN", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ZFIS_PDA_LOGIN_RES SI_MM028_PDA2SAP_LOGIN_OUT([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] ZFIS_PDA_LOGIN_REQ I_IMPORT) {
            object[] results = this.Invoke("SI_MM028_PDA2SAP_LOGIN_OUT", new object[] {
                        I_IMPORT});
            return ((ZFIS_PDA_LOGIN_RES)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSI_MM028_PDA2SAP_LOGIN_OUT(ZFIS_PDA_LOGIN_REQ I_IMPORT, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SI_MM028_PDA2SAP_LOGIN_OUT", new object[] {
                        I_IMPORT}, callback, asyncState);
        }
        
        /// <remarks/>
        public ZFIS_PDA_LOGIN_RES EndSI_MM028_PDA2SAP_LOGIN_OUT(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ZFIS_PDA_LOGIN_RES)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZFIS_PDA_LOGIN_REQ {
        
        private ZIFS_001 zCONTROLField;
        
        private ZFIS_PDA_LOGIN_REQDATA zDATAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ZIFS_001 ZCONTROL {
            get {
                return this.zCONTROLField;
            }
            set {
                this.zCONTROLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ZFIS_PDA_LOGIN_REQDATA ZDATA {
            get {
                return this.zDATAField;
            }
            set {
                this.zDATAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZIFS_001 {
        
        private string gUIDField;
        
        private string iFNUMField;
        
        private string iFDICField;
        
        private string tRSYSField;
        
        private string oRSYSField;
        
        private string iFOPTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GUID {
            get {
                return this.gUIDField;
            }
            set {
                this.gUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IFNUM {
            get {
                return this.iFNUMField;
            }
            set {
                this.iFNUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IFDIC {
            get {
                return this.iFDICField;
            }
            set {
                this.iFDICField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TRSYS {
            get {
                return this.tRSYSField;
            }
            set {
                this.tRSYSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ORSYS {
            get {
                return this.oRSYSField;
            }
            set {
                this.oRSYSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IFOPT {
            get {
                return this.iFOPTField;
            }
            set {
                this.iFOPTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZFIS_PDA_LOGIN_RESDATA {
        
        private string uSERIDField;
        
        private string zPDANAMEField;
        
        private string dEPTNAMEField;
        
        private string tELField;
        
        private string mEMOSField;
        
        private string lGNUMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USERID {
            get {
                return this.uSERIDField;
            }
            set {
                this.uSERIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZPDANAME {
            get {
                return this.zPDANAMEField;
            }
            set {
                this.zPDANAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DEPTNAME {
            get {
                return this.dEPTNAMEField;
            }
            set {
                this.dEPTNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TEL {
            get {
                return this.tELField;
            }
            set {
                this.tELField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MEMOS {
            get {
                return this.mEMOSField;
            }
            set {
                this.mEMOSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LGNUM {
            get {
                return this.lGNUMField;
            }
            set {
                this.lGNUMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZFIS_PDA_LOGIN_RES {
        
        private string gUIDField;
        
        private string bUSNOField;
        
        private string iF_STATUField;
        
        private string iFMSGField;
        
        private ZFIS_PDA_LOGIN_RESDATA dATAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GUID {
            get {
                return this.gUIDField;
            }
            set {
                this.gUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BUSNO {
            get {
                return this.bUSNOField;
            }
            set {
                this.bUSNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IF_STATU {
            get {
                return this.iF_STATUField;
            }
            set {
                this.iF_STATUField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IFMSG {
            get {
                return this.iFMSGField;
            }
            set {
                this.iFMSGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ZFIS_PDA_LOGIN_RESDATA DATA {
            get {
                return this.dATAField;
            }
            set {
                this.dATAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZFIS_PDA_LOGIN_REQDATA {
        
        private string uSERIDField;
        
        private string pASSWORDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USERID {
            get {
                return this.uSERIDField;
            }
            set {
                this.uSERIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PASSWORD {
            get {
                return this.pASSWORDField;
            }
            set {
                this.pASSWORDField = value;
            }
        }
    }
}
